import Nav from "@/components/nav/nav";
import Footer from "@/components/footer/footer";
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: "HongdaeByung",
  description: "Generated by create next app",
};
export default function DefaultLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="relative flex flex-col h-screen">
         <Nav />
        {children}
        <Footer/>
    </div>
  );
}
